POST  http://localhost:5000/api/auth/register
Content-Type:  application/json

{
    "email": "recruiter1@gmail.com",
    "password": "123123",
    "fullname": "Tuan Da",
    "role": "recruiter"
}

###

POST http://localhost:5000/api/auth/login
Content-Type:  application/json

{
    "email": "recruiter1@gmail.com",
    "password": "123123"
}

###
DELETE http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJlbWFpbCI6InBoYW1hbmh0dWFuMjAwNDIwQGdtYWlsLmNvbSIsImlhdCI6MTY2MzY1OTc2NiwiZXhwIjoxNjYzNzQ2MTY2fQ.7cnAugMAq16VCBfIz0o2E4-pdJuLds5UZ5WMgIcwTFM


###
GET http://localhost:5000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoicGhhbWFuaHR1YW4yMDA0MjBAZ21haWwuY29tIiwiaWF0IjoxNjY0MzU5NTMzLCJleHAiOjE2NjQzNjY3MzN9.StSRuUt7aP_80E-Gsfuaorbq4-N7wu-HZ0fv6RXAgb0


###
POST http://localhost:5000/api/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidHVhbmRhMTEwMkBnbWFpbC5jb20iLCJpYXQiOjE2NjQ0OTg0MzgsImV4cCI6MTY2NDUwNTYzOH0.u3mMZYl1cYeDIwChRHSEVQQaZ5ogxk4_9EoxLUo44LM
Content-Type:  application/json

{
    "address": "03 TNV",
    "education": "Duy Tan",
    "description": "Nguoi Ha Tinh"
} 


### JOB
POST http://localhost:5000/api/jobs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImVtYWlsIjoicmVjcnVpdGVyMUBnbWFpbC5jb20iLCJyb2xlIjoicmVjcnVpdGVyIiwiaWF0IjoxNjY0Njk5NjM3LCJleHAiOjE2NjQ3MDY4Mzd9.As4JY-DAcZ4amJ9jXNopdbde3rlB9sTyR2jK6jqVgAc
Content-Type:  application/json

{
    "title": "Front-end Developer",
    "content": "Tao tuyển mày về làm mình làm mẩy oke a ba la trap khè khè khè",
    "salary": "Từ 20 triệu",
    "level": "Senior",
    "skills": "reactjs",
    "location": "Đà nẵng",
    "welfare": "Tăng lương 2 lần 1 năm",
    "gender": "",
    "amount": ,
    "workFrom": "fulltime",
    "endDate": "20/10/2022",
    "isDeleted": false,
    "recruiterId": "5",
    "jobCategoryId": "kinh te"
} 
