POST  http://localhost:5000/api/auth/register
Content-Type:  application/json

{
    "email": "phamanhtuan@gmail.com",
    "password": "123123",
    "fullname": "Tuan Da"
}

###

POST http://localhost:5000/api/auth/login
Content-Type:  application/json

{
    "email": "phamanhtuan@gmail.com",
    "password": "123123"
}

###
DELETE http://localhost:5000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjExLCJlbWFpbCI6InBoYW1hbmh0dWFuMjAwNDIwQGdtYWlsLmNvbSIsImlhdCI6MTY2MzY1OTc2NiwiZXhwIjoxNjYzNzQ2MTY2fQ.7cnAugMAq16VCBfIz0o2E4-pdJuLds5UZ5WMgIcwTFM


###
GET http://localhost:5000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoicGhhbWFuaHR1YW4yMDA0MjBAZ21haWwuY29tIiwiaWF0IjoxNjY0MzU5NTMzLCJleHAiOjE2NjQzNjY3MzN9.StSRuUt7aP_80E-Gsfuaorbq4-N7wu-HZ0fv6RXAgb0


###
POST http://localhost:5000/api/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoidHVhbmRhMTEwMkBnbWFpbC5jb20iLCJpYXQiOjE2NjQ0OTg0MzgsImV4cCI6MTY2NDUwNTYzOH0.u3mMZYl1cYeDIwChRHSEVQQaZ5ogxk4_9EoxLUo44LM
Content-Type:  application/json

{
    "address": "03 TNV",
    "education": "Duy Tan",
    "description": "Nguoi Ha Tinh"
} 


### JOB
POST http://localhost:5000/api/jobs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoicmVjcnVpdGVyMUBnbWFpbC5jb20iLCJyb2xlIjoicmVjcnVpdGVyIiwiaWF0IjoxNjY0NzMyNjI4LCJleHAiOjE2NjQ3Mzk4Mjh9.NI5gpTjpcF9MNCA_Vf_VkplMTn-gYQQvmsPHeneCnz8
Content-Type:  application/json

{
    "title": "Fron-end",
    "content": "Tao tuyển mày về làm mình làm mẩy oke a ba la trap khè khè khè",
    "salary": "Từ 20 triệu",
    "level": "Senior",
    "skills": "reactjs",
    "location": "Đà nẵng",
    "welfare": "Tăng lương 2 lần 1 năm",
    "gender": "",
    "amount": "5 nguoi",
    "workFrom": "fulltime",
    "endDate": "20/10/2022",
    "isDeleted": false,
    "recruiterId": 2,
    "jobCategoryId": 2
} 

###
POST http://localhost:5000/api/jobs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoicGhhbWFuaHR1YW5AZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjQ3MDcwNjcsImV4cCI6MTY2NDcxNDI2N30.EvaURQN_8Njok6PoPlSR1jpKuhw0wBJnD6r6LIIXVD0
Content-Type:  application/json

{
    "title": "suia nha",
    "content": "Đã sửa nek",
    "salary": "Từ Từ rồi tính",
    "level": "okeoke",
    "skills": "reactjs",
    "location": "Hà Tĩnh",
    "welfare": "Tăng lương 2 lần 1 năm",
    "gender": "",
    "amount": "bao nhiêu cũng được",
    "workFrom": "fulltime",
    "endDate": "20/10/2022",
    "isDeleted": false,
    "jobCategoryId": 2
} 

###
DELETE http://localhost:5000/api/jobs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoicmVjcnVpdGVyMUBnbWFpbC5jb20iLCJyb2xlIjoicmVjcnVpdGVyIiwiaWF0IjoxNjY0NzA3NTkyLCJleHAiOjE2NjQ3MTQ3OTJ9.iiZ0lm391Fxhoqc4hFjljum4mZRQMoEc-ufGOE8j0Ns
Content-Type:  application/json

{

} 

### 
GET http://localhost:5000/api/jobs

###
POST http://localhost:5000/api/user/assess
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoicGhhbWFuaHR1YW5AZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE2NjQ3MzI3NTEsImV4cCI6MTY2NDczOTk1MX0.MG_600SAsqa9WnLzMzd5MzRtMjK0Ex2Z1O9c1ee3x1s
Content-Type:  application/json

{
    "message": "Thuc tap sinh khong luong",
    "userId": 1,
    "recruiterId": 1
} 

###
GET http://localhost:5000/api/user/1

